-- MySQL Script generated by MySQL Workbench
-- Tue Mar 28 22:00:28 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema asistencias
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema asistencias
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `asistencias` DEFAULT CHARACTER SET utf8 ;
USE `asistencias` ;

-- -----------------------------------------------------
-- Table `asistencias`.`Periodo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asistencias`.`Periodo` (
  `idperiodo` INT NOT NULL AUTO_INCREMENT,
  `fecInicio` DATETIME NOT NULL,
  `fecFinal` DATETIME NOT NULL,
  `mes` VARCHAR(10) NOT NULL,
  `fecCreate` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `fecChange` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `obs` VARCHAR(200) NULL,
  PRIMARY KEY (`idperiodo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asistencias`.`equipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asistencias`.`equipo` (
  `idequipo` INT NOT NULL AUTO_INCREMENT,
  `nomequipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idequipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asistencias`.`personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asistencias`.`personal` (
  `idpersonal` INT NOT NULL AUTO_INCREMENT,
  `apellidos` VARCHAR(100) NOT NULL,
  `nombres` VARCHAR(80) NOT NULL,
  `dni` CHAR(8) NOT NULL,
  `celular` VARCHAR(12) NOT NULL,
  `grupo` VARCHAR(45) NULL,
  `idequipo` INT NULL,
  `idusuario` INT NULL,
  `periodo_idperiodo` INT NOT NULL,
  `equipo_idequipo` INT NOT NULL,
  PRIMARY KEY (`idpersonal`, `periodo_idperiodo`, `equipo_idequipo`),
  INDEX `fk_personal_Periodo1_idx` (`periodo_idperiodo` ASC),
  INDEX `fk_personal_equipo1_idx` (`equipo_idequipo` ASC) ,
  CONSTRAINT `fk_personal_Periodo1`
    FOREIGN KEY (`periodo_idperiodo`)
    REFERENCES `asistencias`.`Periodo` (`idperiodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_personal_equipo1`
    FOREIGN KEY (`equipo_idequipo`)
    REFERENCES `asistencias`.`equipo` (`idequipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asistencias`.`asistencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asistencias`.`asistencia` (
  `idasistencia` INT NOT NULL AUTO_INCREMENT,
  `periodo_idperiodo` INT NOT NULL,
  `personal_idpersonal` INT NOT NULL,
  `dia` DATE NOT NULL,
  `1as` INT NULL,
  `2as` INT NULL,
  `3as` INT NULL,
  `4as` INT NULL,
  `5as` INT NULL,
  `6as` INT NULL,
  PRIMARY KEY (`idasistencia`, `personal_idpersonal`, `periodo_idperiodo`),
  INDEX `fk_Asistencia_personal1_idx` (`personal_idpersonal` ASC, `periodo_idperiodo` ASC),
  CONSTRAINT `fk_Asistencia_personal1`
    FOREIGN KEY (`personal_idpersonal` , `periodo_idperiodo`)
    REFERENCES `asistencias`.`personal` (`idpersonal` , `periodo_idperiodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asistencias`.`leyenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asistencias`.`leyenda` (
  `idleyenda` INT NOT NULL AUTO_INCREMENT,
  `simbolo` CHAR(4) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `multa` DOUBLE NOT NULL,
  `multacoord` DOUBLE NOT NULL,
  `idasistencia` INT NOT NULL,
  `personal_idpersonal` INT NOT NULL,
  `periodo_idperiodo` INT NOT NULL,
  PRIMARY KEY (`idleyenda`, `idasistencia`, `personal_idpersonal`, `periodo_idperiodo`),
  INDEX `fk_leyenda_Asistencia1_idx` (`idasistencia` ASC, `personal_idpersonal` ASC, `periodo_idperiodo` ASC),
  CONSTRAINT `fk_leyenda_Asistencia1`
    FOREIGN KEY (`idasistencia` , `personal_idpersonal` , `periodo_idperiodo`)
    REFERENCES `asistencias`.`asistencia` (`idasistencia` , `personal_idpersonal` , `periodo_idperiodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asistencias`.`cuartos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asistencias`.`cuartos` (
  `idcuartos` INT NOT NULL AUTO_INCREMENT,
  `idpersonal` INT NOT NULL,
  `numcuarto` INT NOT NULL,
  `personal_idpersonal` INT NOT NULL,
  `periodo_idperiodo` INT NOT NULL,
  PRIMARY KEY (`idcuartos`, `personal_idpersonal`, `periodo_idperiodo`),
  INDEX `fk_cuartos_personal1_idx` (`personal_idpersonal` ASC, `periodo_idperiodo` ASC),
  CONSTRAINT `fk_cuartos_personal1`
    FOREIGN KEY (`personal_idpersonal` , `periodo_idperiodo`)
    REFERENCES `asistencias`.`personal` (`idpersonal` , `periodo_idperiodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asistencias`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asistencias`.`usuarios` (
  `idusuarios` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NULL,
  `personal_idpersonal` INT NOT NULL,
  `periodo_idperiodo` INT NOT NULL,
  PRIMARY KEY (`idusuarios`, `personal_idpersonal`, `periodo_idperiodo`),
  INDEX `fk_usuarios_personal1_idx` (`personal_idpersonal` ASC, `periodo_idperiodo` ASC),
  CONSTRAINT `fk_usuarios_personal1`
    FOREIGN KEY (`personal_idpersonal` , `periodo_idperiodo`)
    REFERENCES `asistencias`.`personal` (`idpersonal` , `periodo_idperiodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
